import type { Metadata } from "next";
import {BaseLayout} from "@/src/widgets/base-layout";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body>
      <NextTopLoader color="#007bff" showSpinner={false} />
      <BaseLayout>
        {children}
      </BaseLayout>
    </body>
    </html>
  );
}
